services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    image: kuldeep265/quicktask-backend:latest
    restart: unless-stopped
    ports:
      - "5002:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: kuldeep265/quicktask-frontend:latest
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
