services:

  frontend:
    image: kuldeep7860/quicktask-frontend:latest

    container_name: frontend

    ports:
      - "3002:3000"

    depends_on:
      - backend

  backend:
    image: kuldeep7860/quicktask-backend:latest

    container_name: backend

    ports:
      - "5002:5000"

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest

    container_name: mongodb

    ports:
      - "27017:27017"















# services:

#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3002:3000"
#     depends_on:
#       - backend

#   backend:
#     build: ./backend
#     container_name: backend
#     ports:
#       - "5002:5000"
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"



